# Update robottelo image on quay.
name: update_robottelo_image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  robottelo_container:
    name: Update Robottelo container image on Quay.
    runs-on: ubuntu-latest

    steps:
      - name: Get tag
        id: repo_tag
        run: |
          TAG="${GITHUB_REF##*/}"
          echo "REPO_TAG=$TAG" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v3

      - name: Update tag info
        id: image_tag
        run: |
          TAG=${{ steps.repo_tag.outputs.REPO_TAG }}
          TAG=${TAG/main/latest}
          echo "IMAGE_TAG=$TAG" >> $GITHUB_OUTPUT

      - name: assert
        run: |
          echo "IMAGE_TAG: ${{ steps.image_tag.outputs.IMAGE_TAG }}"
          echo "GITHUB_REF: ${{ steps.repo_tag.outputs.REPO_TAG }}"
